<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>ICG.NetCore.Utilities.Email.Smtp</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ICG.NetCore.Utilities.Email.Smtp</PackageId>
    <Title>NetCore Utilities Email SMTP</Title>
    <Description>A library providing easy access to sending emails, including templated emails, via SMTP from .NET 9+.</Description>
    <Copyright>Copyright 2025, IowaComputerGurus, Inc. All Rights Reserved</Copyright>
    <PackageProjectUrl>https://github.com/IowaComputerGurus/netcore.utilities.email.smtp</PackageProjectUrl>
    <PackageTags>aspnetcore;utility;email</PackageTags>
    <RepositoryUrl>https://github.com/IowaComputerGurus/netcore.utilities.email.smtp</RepositoryUrl>
    <Authors>MitchelSellers;IowaComputerGurus</Authors>
    <Owners>IowaComputerGurus</Owners>
	<PackageIcon>icgAppIcon.png</PackageIcon>
    <IsPackable>True</IsPackable>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
	<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <ItemGroup>
	<None Include="icgAppIcon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="icg.netcore.utilities.email" Version="9.0.0" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.0" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
